"""add_mobux_trust_competitor_scores_and_pricing_config

Revision ID: d3a9af3a0e44
Revises: 
Create Date: 2026-02-10 10:46:25.286906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a9af3a0e44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('unlock_price', sa.Float(), nullable=True),
    sa.Column('quick_wins_price', sa.Float(), nullable=True),
    sa.Column('monitor_monthly', sa.Float(), nullable=True),
    sa.Column('campaign_price', sa.Float(), nullable=True),
    sa.Column('campaign_ends_at', sa.DateTime(), nullable=True),
    sa.Column('campaign_label', sa.String(length=255), nullable=True),
    sa.Column('normal_unlock_price', sa.Float(), nullable=True),
    sa.Column('normal_full_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_config_market'), ['market'], unique=False)

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_ux_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trust_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('competitor_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('competitor_score')
        batch_op.drop_column('trust_score')
        batch_op.drop_column('mobile_ux_score')

    with op.batch_alter_table('pricing_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_config_market'))

    op.drop_table('pricing_config')
    # ### end Alembic commands ###
